stages:
  train:
    cmd: python src/train.py --model_type ${train.model_type}
    deps:
      - data/df_clean.parquet
      - src/pipeline.py
      - src/train.py
      - src/utils.py
    params:
      - train
      - logistic
      - random_forest
    outs:
      - models/model.joblib
      - data/processed/train.parquet
      - data/processed/test.parquet

  evaluation:
    cmd: python src/evaluation.py --evaluate --report_path reports/classification_report.txt --metrics_path reports/metrics.json
    deps:
      - src/evaluation.py
      - src/utils.py
      - data/processed/test.parquet
      - models/model.joblib
    params:
      - data # evaluation.py reads params.yaml to get the test data path
    outs:
      - reports/classification_report.txt
    metrics:
      - reports/metrics.json:
          cache: false