stages:
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - data/df_clean.parquet
      - src/data_preprocessing.py
      - src/utils.py
    params:
      - train.test_split_ratio
      - train.random_state
      - train.stratify
      - train.label_col
      - features
    outs:
      - data/processed/train.parquet
      - data/processed/test.parquet

  model_training:
    cmd: python src/model_training.py --model_type ${train.model_type}
    deps:
      - data/processed/train.parquet
      - src/feature_engineering.py
      - src/model_training.py
      - src/utils.py
    params:
      - train.model_type
      - train.smote_random_state
      - train.label_col
      - features
      - logistic
      - random_forest
    outs:
      - models/model.joblib

  model_evaluation:
    cmd: python src/model_evaluation.py --evaluate --report_path reports/classification_report.txt --metrics_path reports/metrics.json
    deps:
      - src/model_evaluation.py
      - src/utils.py
      - models/model.joblib
      - data/processed/test.parquet
    params:
      - train # For logging params
      - logistic
      - random_forest
    outs:
      - reports/classification_report.txt
    metrics:
      - reports/metrics.json:
          cache: false
    plots:
      - reports/confusion_matrix.png:
          cache: false