# params.yaml

data:
  raw_path: "data/df_clean.parquet"
  train_path: "data/processed/train.parquet"
  test_path: "data/processed/test.parquet"


train:
  model_type: random_forest    # 'logistic' or 'random_forest'
  test_split_ratio: 0.2
  random_state: 42
  stratify: true
  smote_random_state: 42
  decision_threshold: 0.60

features:
  categorical:
    - home_status
    - loan_intent
    - loan_grade
  numerical:
    - income
    - emp_years
    - loan_amount
    - loan_int_rate
    - loan_percent_income
    - credit_history

logistic:
  solver: liblinear
  penalty: l2
  C: 0.34
  max_iter: 1290
  class_weight: balanced

random_forest:
  max_features: 5
  n_estimators: 405
  class_weight: balanced
  max_depth: 8
  min_samples_split: 2
  min_samples_leaf: 1